server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/customer #This is for deployment
    # url: jdbc:postgresql://db:5332/customer  #This is for docker
    # url: jdbc:postgresql://localhost:5332/customer #This is for IT classes
    username: dollarstore
    password: password
  jpa:
    hibernate:
      ddl-auto: update #Deployment
      # ddl-auto: create-drop #IT classes

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: cristianjoelbuldapoblete@gmail.com
    password: jxne cgfu mrsg lzor
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  main:
    web-application-type: servlet
